# Generated by Django 5.1.6 on 2025-02-23 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_rename_created_at_file_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour un drive personnel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drives', to=settings.AUTH_USER_MODEL),
        ),
    ]
