# Generated by Django 5.1.6 on 2025-03-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_file_owner'),
        ('photo', '0002_photo_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='explorer.file'),
        ),
    ]
