# Generated by Django 5.1.6 on 2025-03-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_file_owner'),
        ('photo', '0003_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='explorer.file'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
